### ISSUE TITLE
Plugin stops Query Monitor from outputting

### ISSUE THREAD

**Issue by Beee4life** [timber/debug-bar-timber#14]
It appears that your plugin stops the plugin Query Monitor from outputting on some post archive pages. As referenced in [this topic](https://github.com/johnbillion/query-monitor/issues/295).

I don't know what causes it, all I know is when I deactivate the debug-bar-timber plugin it shows as expected.

**Comment by manzwebdesigns** [comment]
I just installed Query Monitor and there is no issues with the newest (soon to be released) toolbar so I am closing this as fixed. @Beee4life @jarednova please let me know if you find otherwise!

**Comment by Beee4life** [comment]
When can we expect this release @manzwebdesigns ?

**Comment by manzwebdesigns** [comment]
@Beee4life, I will do my best to get this done today.

**Comment by Beee4life** [comment]
Awesome, can't wait to test it out...

**Comment by manzwebdesigns** [comment]
@Beee4life  Release 1.0.0 is published at https://github.com/timber/debug-bar-timber/releases/latest! Come and get it!

**Comment by Beee4life** [comment]
I just realised that my conflict came from a site which uses the plugin events manager. That site will be deactivated within a month or so because I discontinued it due to lack of time. So can't really test it out right away, nor do I have the problem :)

**Comment by manzwebdesigns** [comment]
Sounds good, it would be interesting to see if it fixed it though :)
On 7/25/2020 4:54:55 PM, Beee <notifications@github.com> wrote:
I just realised that my conflict came from a site which uses the plugin events manager. That site will be deactivated within a month or so because I discontinued it due to lack of time. So can't really test it out right away, nor do I have the problem :)
